backend = "wayland"
transition_mode = "finish_by"   #"geo"

smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

day_gamma = 101
day_temp = 6000

night_gamma = 60
night_temp = 2000

update_interval = "auto"

sunset = "22:00:00"      
sunrise = "06:00:00"    
transition_duration = 60 # Transition duration in minutes (5-120)

latitude = 60
longitude = 10
