-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/
local wezterm = require("wezterm")
local config = wezterm.config_builder and wezterm.config_builder() or {}

local hm_config = {
	adjust_window_size_when_changing_font_size = false,
	cell_width = 1.0,
	enable_scroll_bar = false,
	hide_tab_bar_if_only_one_tab = true,
	line_height = 0.9,
	use_fancy_tab_bar = false,
	window_close_confirmation = "NeverPrompt",
	window_decorations = "NONE",
	window_padding = {
		bottom = 0,
		left = 4,
		right = 4,
		top = 0,
	},
	colors = {
		ansi = {
			"#1E1E1E",
			"#DC6666",
			"#86B895",
			"#E0B879",
			"#7DAAEA",
			"#CFA1E8",
			"#DC6666",
			"#E3E0E0",
		},
		brights = {
			"#1E1E1E",
			"#DC6666",
			"#86B895",
			"#E0B879",
			"#7DAAEA",
			"#CFA1E8",
			"#DC6666",
			"#E3E0E0",
		},
		background = "#1E1E1E",
		foreground = "#E3E0E0",
		cursor_bg = "#DC6666",
		cursor_border = "#DC6666",
		cursor_fg = "#1E1E1E",
		selection_bg = "#DC6666",
		selection_fg = "#1E1E1E",
	},
}

for k, v in pairs(hm_config) do
	config[k] = v
end

return config
