let
  acerkey = (import ./Acer.nix).sshkey;
  dellkey = (import ./Dell.nix).sshkey;
  lenovokey = (import ./Lenovo.nix).sshkey;
  wslzbookkey = (import ./WSLZbook.nix).sshkey;
  wslT2000key = (import ./WSLT2000.nix).sshkey;
  wslworkkey = (import ./WSLWork.nix).sshkey;
in
rec {
  zbookkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFVOm4q1/v7MNNsnf6iNlFYUXsV/kxkAzmleWgd6JOr7 sofushl@ZBook";
  phonekey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJkuDY1S0ygCOKVK1L+u4Cn2HfJlsFOZZ2MkkiIEscP Generated By Termius";
  tvkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPUbk0QgUO3d5o7zKqHacseqALt1AlKZkQJj2FcRRcsm soli@tv";

  sshkeys = [
    acerkey
    dellkey
    lenovokey
    wslzbookkey
    wslT2000key
    wslworkkey
    zbookkey
    phonekey
    tvkey
  ];
}
