let
  T2000key = (import ./T2000.nix).sshkey;

  laptops = import ./laptops.nix;
  resolvelaptop = builtins.mapAttrs (_: h: laptops.default // h) laptops.hosts;
  laptopkeys = builtins.filter (k: k != null) (map (h: h.key) (builtins.attrValues resolvelaptop));

  homes = import ./homes.nix;
  resolvehome = builtins.mapAttrs (_: h: homes.default // h) homes.homes;
  homekeys = builtins.filter (k: k != null) (map (h: h.key) (builtins.attrValues resolvehome));
in
rec {
  phonekey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJkuDY1S0ygCOKVK1L+u4Cn2HfJlsFOZZ2MkkiIEscP Generated By Termius";
  winkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPkgE78Nlc92AUcetKRsdpo9jOBzDYO/DhCgYlixvPDX sofushl@Win";

  sshkeys = [
    T2000key
    phonekey
    winkey
  ]
  ++ laptopkeys
  ++ homekeys;
}
